// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// bgnbd_nocov_CET
arma::vec bgnbd_nocov_CET(const double r, const double alpha, const double a, const double b, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_bgnbd_nocov_CET(SEXP rSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_nocov_CET(r, alpha, a, b, dPeriods, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_CET
arma::vec bgnbd_staticcov_CET(const double r, const double alpha, const double a, const double b, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_trans, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_bgnbd_staticcov_CET(SEXP rSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_transSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_CET(r, alpha, a, b, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_nocov_LL_ind
arma::vec bgnbd_nocov_LL_ind(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_bgnbd_nocov_LL_ind(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_nocov_LL_ind(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_nocov_LL_sum
double bgnbd_nocov_LL_sum(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_bgnbd_nocov_LL_sum(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_nocov_LL_sum(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_LL_ind
arma::vec bgnbd_staticcov_LL_ind(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_bgnbd_staticcov_LL_ind(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_LL_ind(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_LL_sum
double bgnbd_staticcov_LL_sum(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_bgnbd_staticcov_LL_sum(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_LL_sum(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_alpha_i
arma::vec bgnbd_staticcov_alpha_i(const double alpha_0, const arma::vec& vCovParams_trans, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_bgnbd_staticcov_alpha_i(SEXP alpha_0SEXP, SEXP vCovParams_transSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_alpha_i(alpha_0, vCovParams_trans, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_a_i
arma::vec bgnbd_staticcov_a_i(const double a_0, const arma::vec& vCovParams_life, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_bgnbd_staticcov_a_i(SEXP a_0SEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type a_0(a_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_a_i(a_0, vCovParams_life, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_b_i
arma::vec bgnbd_staticcov_b_i(const double b_0, const arma::vec& vCovParams_life, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_bgnbd_staticcov_b_i(SEXP b_0SEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type b_0(b_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_b_i(b_0, vCovParams_life, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_nocov_PAlive
arma::vec bgnbd_nocov_PAlive(const double r, const double alpha, const double a, const double b, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_bgnbd_nocov_PAlive(SEXP rSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_nocov_PAlive(r, alpha, a, b, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_PAlive
arma::vec bgnbd_staticcov_PAlive(const double r, const double alpha, const double a, const double b, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_trans, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_bgnbd_staticcov_PAlive(SEXP rSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_transSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_PAlive(r, alpha, a, b, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_nocov_expectation
arma::vec bgnbd_nocov_expectation(const double r, const double alpha, const double a, const double b, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_bgnbd_nocov_expectation(SEXP rSEXP, SEXP alphaSEXP, SEXP aSEXP, SEXP bSEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_nocov_expectation(r, alpha, a, b, vT_i));
    return rcpp_result_gen;
END_RCPP
}
// bgnbd_staticcov_expectation
arma::vec bgnbd_staticcov_expectation(const double r, const arma::vec& vAlpha_i, const arma::vec& vA_i, const arma::vec& vB_i, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_bgnbd_staticcov_expectation(SEXP rSEXP, SEXP vAlpha_iSEXP, SEXP vA_iSEXP, SEXP vB_iSEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vAlpha_i(vAlpha_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vA_i(vA_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vB_i(vB_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(bgnbd_staticcov_expectation(r, vAlpha_i, vA_i, vB_i, vT_i));
    return rcpp_result_gen;
END_RCPP
}
// vec_gsl_hyp2f0_e
Rcpp::List vec_gsl_hyp2f0_e(const RcppGSL::Vector& vA, const RcppGSL::Vector& vB, const RcppGSL::Vector& vZ);
RcppExport SEXP _CLVTools_vec_gsl_hyp2f0_e(SEXP vASEXP, SEXP vBSEXP, SEXP vZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vA(vASEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vB(vBSEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vZ(vZSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_gsl_hyp2f0_e(vA, vB, vZ));
    return rcpp_result_gen;
END_RCPP
}
// vec_gsl_hyp2f1_e
Rcpp::List vec_gsl_hyp2f1_e(const RcppGSL::Vector& vA, const RcppGSL::Vector& vB, const RcppGSL::Vector& vC, const RcppGSL::Vector& vZ);
RcppExport SEXP _CLVTools_vec_gsl_hyp2f1_e(SEXP vASEXP, SEXP vBSEXP, SEXP vCSEXP, SEXP vZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vA(vASEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vB(vBSEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vC(vCSEXP);
    Rcpp::traits::input_parameter< const RcppGSL::Vector& >::type vZ(vZSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_gsl_hyp2f1_e(vA, vB, vC, vZ));
    return rcpp_result_gen;
END_RCPP
}
// gg_LL
double gg_LL(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vM_x);
RcppExport SEXP _CLVTools_gg_LL(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vM_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vM_x(vM_xSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_LL(vLogparams, vX, vM_x));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_nocov_CET
arma::vec ggomnbd_nocov_CET(const double r, const double alpha_0, const double b, const double s, const double beta_0, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_ggomnbd_nocov_CET(SEXP rSEXP, SEXP alpha_0SEXP, SEXP bSEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_nocov_CET(r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_CET
arma::vec ggomnbd_staticcov_CET(const double r, const double alpha_0, const double b, const double s, const double beta_0, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_CET(SEXP rSEXP, SEXP alpha_0SEXP, SEXP bSEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_CET(r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_nocov_LL_ind
arma::vec ggomnbd_nocov_LL_ind(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_ggomnbd_nocov_LL_ind(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_nocov_LL_ind(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_nocov_LL_sum
double ggomnbd_nocov_LL_sum(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_ggomnbd_nocov_LL_sum(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_nocov_LL_sum(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_LL_ind
arma::vec ggomnbd_staticcov_LL_ind(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_LL_ind(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_LL_ind(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_LL_sum
double ggomnbd_staticcov_LL_sum(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_LL_sum(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_LL_sum(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_alpha_i
arma::vec ggomnbd_staticcov_alpha_i(const double alpha_0, const arma::vec& vCovParams_trans, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_alpha_i(SEXP alpha_0SEXP, SEXP vCovParams_transSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_alpha_i(alpha_0, vCovParams_trans, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_beta_i
arma::vec ggomnbd_staticcov_beta_i(const double beta_0, const arma::vec& vCovParams_life, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_beta_i(SEXP beta_0SEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_beta_i(beta_0, vCovParams_life, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_PAlive
arma::vec ggomnbd_staticcov_PAlive(const double r, const double alpha_0, const double b, const double s, const double beta_0, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_PAlive(SEXP rSEXP, SEXP alpha_0SEXP, SEXP bSEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_PAlive(r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_nocov_PAlive
arma::vec ggomnbd_nocov_PAlive(const double r, const double alpha_0, const double b, const double s, const double beta_0, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_ggomnbd_nocov_PAlive(SEXP rSEXP, SEXP alpha_0SEXP, SEXP bSEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_nocov_PAlive(r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_nocov_expectation
arma::vec ggomnbd_nocov_expectation(const double r, const double alpha_0, const double b, const double s, const double beta_0, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_ggomnbd_nocov_expectation(SEXP rSEXP, SEXP alpha_0SEXP, SEXP bSEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_nocov_expectation(r, alpha_0, b, s, beta_0, vT_i));
    return rcpp_result_gen;
END_RCPP
}
// ggomnbd_staticcov_expectation
arma::vec ggomnbd_staticcov_expectation(const double r, const double b, const double s, const arma::vec& vAlpha_i, const arma::vec& vBeta_i, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_ggomnbd_staticcov_expectation(SEXP rSEXP, SEXP bSEXP, SEXP sSEXP, SEXP vAlpha_iSEXP, SEXP vBeta_iSEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vAlpha_i(vAlpha_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vBeta_i(vBeta_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(ggomnbd_staticcov_expectation(r, b, s, vAlpha_i, vBeta_i, vT_i));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_CET
arma::vec pnbd_nocov_CET(const double r, const double alpha_0, const double s, const double beta_0, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_pnbd_nocov_CET(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_CET(r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_CET
arma::vec pnbd_staticcov_CET(const double r, const double alpha_0, const double s, const double beta_0, const double dPeriods, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_trans, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_pnbd_staticcov_CET(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP dPeriodsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_transSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type dPeriods(dPeriodsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_CET(r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_DERT
arma::vec pnbd_nocov_DERT(const double r, const double alpha_0, const double s, const double beta_0, const double continuous_discount_factor, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_pnbd_nocov_DERT(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP continuous_discount_factorSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type continuous_discount_factor(continuous_discount_factorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_DERT(r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_DERT
arma::vec pnbd_staticcov_DERT(const double r, const double alpha_0, const double s, const double beta_0, const double continuous_discount_factor, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans, const arma::vec& vCovParams_life, const arma::vec& vCovParams_trans);
RcppExport SEXP _CLVTools_pnbd_staticcov_DERT(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP continuous_discount_factorSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP, SEXP vCovParams_lifeSEXP, SEXP vCovParams_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const double >::type continuous_discount_factor(continuous_discount_factorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_DERT(r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal, mCov_life, mCov_trans, vCovParams_life, vCovParams_trans));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_LL_ind
arma::vec pnbd_nocov_LL_ind(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_pnbd_nocov_LL_ind(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_LL_ind(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_LL_sum
double pnbd_nocov_LL_sum(const arma::vec& vLogparams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_pnbd_nocov_LL_sum(SEXP vLogparamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vLogparams(vLogparamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_LL_sum(vLogparams, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_LL_ind
arma::vec pnbd_staticcov_LL_ind(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_pnbd_staticcov_LL_ind(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_LL_ind(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_LL_sum
double pnbd_staticcov_LL_sum(const arma::vec& vParams, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::mat& mCov_life, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_pnbd_staticcov_LL_sum(SEXP vParamsSEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP mCov_lifeSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vParams(vParamsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_LL_sum(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_alpha_i
arma::vec pnbd_staticcov_alpha_i(const double alpha_0, const arma::vec& vCovParams_trans, const arma::mat& mCov_trans);
RcppExport SEXP _CLVTools_pnbd_staticcov_alpha_i(SEXP alpha_0SEXP, SEXP vCovParams_transSEXP, SEXP mCov_transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_alpha_i(alpha_0, vCovParams_trans, mCov_trans));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_beta_i
arma::vec pnbd_staticcov_beta_i(const double beta_0, const arma::vec& vCovParams_life, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_pnbd_staticcov_beta_i(SEXP beta_0SEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_beta_i(beta_0, vCovParams_life, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_PAlive
arma::vec pnbd_nocov_PAlive(const double r, const double alpha_0, const double s, const double beta_0, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal);
RcppExport SEXP _CLVTools_pnbd_nocov_PAlive(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_PAlive(r, alpha_0, s, beta_0, vX, vT_x, vT_cal));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_PAlive
arma::vec pnbd_staticcov_PAlive(const double r, const double alpha_0, const double s, const double beta_0, const arma::vec& vX, const arma::vec& vT_x, const arma::vec& vT_cal, const arma::vec& vCovParams_trans, const arma::vec& vCovParams_life, const arma::mat& mCov_trans, const arma::mat& mCov_life);
RcppExport SEXP _CLVTools_pnbd_staticcov_PAlive(SEXP rSEXP, SEXP alpha_0SEXP, SEXP sSEXP, SEXP beta_0SEXP, SEXP vXSEXP, SEXP vT_xSEXP, SEXP vT_calSEXP, SEXP vCovParams_transSEXP, SEXP vCovParams_lifeSEXP, SEXP mCov_transSEXP, SEXP mCov_lifeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vX(vXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_x(vT_xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_cal(vT_calSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_trans(vCovParams_transSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vCovParams_life(vCovParams_lifeSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_trans(mCov_transSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mCov_life(mCov_lifeSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_PAlive(r, alpha_0, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_nocov_expectation
arma::vec pnbd_nocov_expectation(const double r, const double s, const double alpha_0, const double beta_0, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_pnbd_nocov_expectation(SEXP rSEXP, SEXP sSEXP, SEXP alpha_0SEXP, SEXP beta_0SEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< const double >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_nocov_expectation(r, s, alpha_0, beta_0, vT_i));
    return rcpp_result_gen;
END_RCPP
}
// pnbd_staticcov_expectation
arma::vec pnbd_staticcov_expectation(const double r, const double s, const arma::vec& vAlpha_i, const arma::vec& vBeta_i, const arma::vec& vT_i);
RcppExport SEXP _CLVTools_pnbd_staticcov_expectation(SEXP rSEXP, SEXP sSEXP, SEXP vAlpha_iSEXP, SEXP vBeta_iSEXP, SEXP vT_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type r(rSEXP);
    Rcpp::traits::input_parameter< const double >::type s(sSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vAlpha_i(vAlpha_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vBeta_i(vBeta_iSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vT_i(vT_iSEXP);
    rcpp_result_gen = Rcpp::wrap(pnbd_staticcov_expectation(r, s, vAlpha_i, vBeta_i, vT_i));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CLVTools_bgnbd_nocov_CET", (DL_FUNC) &_CLVTools_bgnbd_nocov_CET, 8},
    {"_CLVTools_bgnbd_staticcov_CET", (DL_FUNC) &_CLVTools_bgnbd_staticcov_CET, 12},
    {"_CLVTools_bgnbd_nocov_LL_ind", (DL_FUNC) &_CLVTools_bgnbd_nocov_LL_ind, 4},
    {"_CLVTools_bgnbd_nocov_LL_sum", (DL_FUNC) &_CLVTools_bgnbd_nocov_LL_sum, 4},
    {"_CLVTools_bgnbd_staticcov_LL_ind", (DL_FUNC) &_CLVTools_bgnbd_staticcov_LL_ind, 6},
    {"_CLVTools_bgnbd_staticcov_LL_sum", (DL_FUNC) &_CLVTools_bgnbd_staticcov_LL_sum, 6},
    {"_CLVTools_bgnbd_staticcov_alpha_i", (DL_FUNC) &_CLVTools_bgnbd_staticcov_alpha_i, 3},
    {"_CLVTools_bgnbd_staticcov_a_i", (DL_FUNC) &_CLVTools_bgnbd_staticcov_a_i, 3},
    {"_CLVTools_bgnbd_staticcov_b_i", (DL_FUNC) &_CLVTools_bgnbd_staticcov_b_i, 3},
    {"_CLVTools_bgnbd_nocov_PAlive", (DL_FUNC) &_CLVTools_bgnbd_nocov_PAlive, 7},
    {"_CLVTools_bgnbd_staticcov_PAlive", (DL_FUNC) &_CLVTools_bgnbd_staticcov_PAlive, 11},
    {"_CLVTools_bgnbd_nocov_expectation", (DL_FUNC) &_CLVTools_bgnbd_nocov_expectation, 5},
    {"_CLVTools_bgnbd_staticcov_expectation", (DL_FUNC) &_CLVTools_bgnbd_staticcov_expectation, 5},
    {"_CLVTools_vec_gsl_hyp2f0_e", (DL_FUNC) &_CLVTools_vec_gsl_hyp2f0_e, 3},
    {"_CLVTools_vec_gsl_hyp2f1_e", (DL_FUNC) &_CLVTools_vec_gsl_hyp2f1_e, 4},
    {"_CLVTools_gg_LL", (DL_FUNC) &_CLVTools_gg_LL, 3},
    {"_CLVTools_ggomnbd_nocov_CET", (DL_FUNC) &_CLVTools_ggomnbd_nocov_CET, 9},
    {"_CLVTools_ggomnbd_staticcov_CET", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_CET, 13},
    {"_CLVTools_ggomnbd_nocov_LL_ind", (DL_FUNC) &_CLVTools_ggomnbd_nocov_LL_ind, 4},
    {"_CLVTools_ggomnbd_nocov_LL_sum", (DL_FUNC) &_CLVTools_ggomnbd_nocov_LL_sum, 4},
    {"_CLVTools_ggomnbd_staticcov_LL_ind", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_LL_ind, 6},
    {"_CLVTools_ggomnbd_staticcov_LL_sum", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_LL_sum, 6},
    {"_CLVTools_ggomnbd_staticcov_alpha_i", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_alpha_i, 3},
    {"_CLVTools_ggomnbd_staticcov_beta_i", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_beta_i, 3},
    {"_CLVTools_ggomnbd_staticcov_PAlive", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_PAlive, 12},
    {"_CLVTools_ggomnbd_nocov_PAlive", (DL_FUNC) &_CLVTools_ggomnbd_nocov_PAlive, 8},
    {"_CLVTools_ggomnbd_nocov_expectation", (DL_FUNC) &_CLVTools_ggomnbd_nocov_expectation, 6},
    {"_CLVTools_ggomnbd_staticcov_expectation", (DL_FUNC) &_CLVTools_ggomnbd_staticcov_expectation, 6},
    {"_CLVTools_pnbd_nocov_CET", (DL_FUNC) &_CLVTools_pnbd_nocov_CET, 8},
    {"_CLVTools_pnbd_staticcov_CET", (DL_FUNC) &_CLVTools_pnbd_staticcov_CET, 12},
    {"_CLVTools_pnbd_nocov_DERT", (DL_FUNC) &_CLVTools_pnbd_nocov_DERT, 8},
    {"_CLVTools_pnbd_staticcov_DERT", (DL_FUNC) &_CLVTools_pnbd_staticcov_DERT, 12},
    {"_CLVTools_pnbd_nocov_LL_ind", (DL_FUNC) &_CLVTools_pnbd_nocov_LL_ind, 4},
    {"_CLVTools_pnbd_nocov_LL_sum", (DL_FUNC) &_CLVTools_pnbd_nocov_LL_sum, 4},
    {"_CLVTools_pnbd_staticcov_LL_ind", (DL_FUNC) &_CLVTools_pnbd_staticcov_LL_ind, 6},
    {"_CLVTools_pnbd_staticcov_LL_sum", (DL_FUNC) &_CLVTools_pnbd_staticcov_LL_sum, 6},
    {"_CLVTools_pnbd_staticcov_alpha_i", (DL_FUNC) &_CLVTools_pnbd_staticcov_alpha_i, 3},
    {"_CLVTools_pnbd_staticcov_beta_i", (DL_FUNC) &_CLVTools_pnbd_staticcov_beta_i, 3},
    {"_CLVTools_pnbd_nocov_PAlive", (DL_FUNC) &_CLVTools_pnbd_nocov_PAlive, 7},
    {"_CLVTools_pnbd_staticcov_PAlive", (DL_FUNC) &_CLVTools_pnbd_staticcov_PAlive, 11},
    {"_CLVTools_pnbd_nocov_expectation", (DL_FUNC) &_CLVTools_pnbd_nocov_expectation, 5},
    {"_CLVTools_pnbd_staticcov_expectation", (DL_FUNC) &_CLVTools_pnbd_staticcov_expectation, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CLVTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
