# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name bgnbd_CET
#'
#' @templateVar name_model_full BG/NBD
#' @templateVar name_model_short bgnbd
#' @template template_titledescriptionreturn_CET
#'
#' @template template_params_bgnbd
#' @template template_params_rcppperiods
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_bgnbd
#'
NULL

#' @name bgnbd_expectation
#' @title BG/NBD: Unconditional Expectation
#'
#' @template template_expectation_description
#'
#' @template template_params_bgnbd
#' @template template_expectation_params
#' @param vAlpha_i Vector of individual parameters alpha
#' @param vA_i Vector of individual parameters a
#' @param vB_i Vector of individual parameters b
#'
#' @template template_references_bgnbd
#'
#' @template template_expectation_return
#'
NULL

#' @name bgnbd_PAlive
#'
#' @templateVar name_model_full BG/NBD
#' @templateVar name_model_short bgnbd
#' @template template_titledescriptionreturn_palive
#'
#' @template template_params_bgnbd
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_bgnbd
#'
NULL

#' @name bgnbd_LL
#'
#' @templateVar name_model_full BG/NBD
#' @templateVar name_model_short bgnbd
#' @templateVar model_params_ordered r, alpha_0, a, b
#' @template template_titleparamsdescriptionreturndetails_LL
#'
#' @template template_params_rcppxtxtcal
#' @template template_param_rcppvn
#' @template template_params_rcppcovmatrix
#'
#' @templateVar name_params_cov_life vLogparams
#' @templateVar name_params_cov_trans vLogparams
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_bgnbd
#'
NULL

#' @name bgnbd_pmf
#' @templateVar name_model_full BG/NBD
#' @template template_pmf_titledescreturnpmfparams
#' @template template_params_bgnbd
#' @param vAlpha_i Vector of individual parameters alpha
#' @param vA_i Vector of individual parameters a
#' @param vB_i Vector of individual parameters b
#' @template template_references_bgnbd
#'
NULL

#' @rdname bgnbd_CET
bgnbd_nocov_CET <- function(r, alpha, a, b, dPeriods, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_bgnbd_nocov_CET`, r, alpha, a, b, dPeriods, vX, vT_x, vT_cal)
}

#' @rdname bgnbd_CET
bgnbd_staticcov_CET <- function(r, alpha, a, b, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life) {
    .Call(`_CLVTools_bgnbd_staticcov_CET`, r, alpha, a, b, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life)
}

#' @rdname bgnbd_expectation
bgnbd_nocov_expectation <- function(r, alpha, a, b, vT_i) {
    .Call(`_CLVTools_bgnbd_nocov_expectation`, r, alpha, a, b, vT_i)
}

#' @rdname bgnbd_expectation
bgnbd_staticcov_expectation <- function(r, vAlpha_i, vA_i, vB_i, vT_i) {
    .Call(`_CLVTools_bgnbd_staticcov_expectation`, r, vAlpha_i, vA_i, vB_i, vT_i)
}

#' @rdname bgnbd_PAlive
bgnbd_nocov_PAlive <- function(r, alpha, a, b, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_bgnbd_nocov_PAlive`, r, alpha, a, b, vX, vT_x, vT_cal)
}

#' @rdname bgnbd_PAlive
bgnbd_staticcov_PAlive <- function(r, alpha, a, b, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life) {
    .Call(`_CLVTools_bgnbd_staticcov_PAlive`, r, alpha, a, b, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life)
}

#' @rdname bgnbd_LL
bgnbd_nocov_LL_ind <- function(vLogparams, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_bgnbd_nocov_LL_ind`, vLogparams, vX, vT_x, vT_cal)
}

#' @rdname bgnbd_LL
bgnbd_nocov_LL_sum <- function(vLogparams, vX, vT_x, vT_cal, vN) {
    .Call(`_CLVTools_bgnbd_nocov_LL_sum`, vLogparams, vX, vT_x, vT_cal, vN)
}

#' @rdname bgnbd_LL
bgnbd_staticcov_LL_ind <- function(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans) {
    .Call(`_CLVTools_bgnbd_staticcov_LL_ind`, vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans)
}

#' @rdname bgnbd_LL
bgnbd_staticcov_LL_sum <- function(vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans) {
    .Call(`_CLVTools_bgnbd_staticcov_LL_sum`, vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans)
}

#' @rdname bgnbd_pmf
bgnbd_nocov_PMF <- function(r, alpha, a, b, x, vT_i) {
    .Call(`_CLVTools_bgnbd_nocov_PMF`, r, alpha, a, b, x, vT_i)
}

#' @rdname bgnbd_pmf
bgnbd_staticcov_PMF <- function(r, x, vAlpha_i, vA_i, vB_i, vT_i) {
    .Call(`_CLVTools_bgnbd_staticcov_PMF`, r, x, vAlpha_i, vA_i, vB_i, vT_i)
}

bgnbd_staticcov_alpha_i <- function(alpha_0, vCovParams_trans, mCov_trans) {
    .Call(`_CLVTools_bgnbd_staticcov_alpha_i`, alpha_0, vCovParams_trans, mCov_trans)
}

bgnbd_staticcov_a_i <- function(a_0, vCovParams_life, mCov_life) {
    .Call(`_CLVTools_bgnbd_staticcov_a_i`, a_0, vCovParams_life, mCov_life)
}

bgnbd_staticcov_b_i <- function(b_0, vCovParams_life, mCov_life) {
    .Call(`_CLVTools_bgnbd_staticcov_b_i`, b_0, vCovParams_life, mCov_life)
}

#' @title GSL Hypergeometric 2F0 for equal length vectors
#'
#' @param vA Vector of values for parameter a
#' @param vB Vector of values for parameter b
#' @param vZ Vector of values for parameter z
#'
#' @description Calculate the hypergeometric 2f0 using the GSL library (gsl_sf_hyperg_2F0_e)
#' @return List with vector of values and vector of gsl status codes
#' @keywords internal
vec_gsl_hyp2f0_e <- function(vA, vB, vZ) {
    .Call(`_CLVTools_vec_gsl_hyp2f0_e`, vA, vB, vZ)
}

#' @title GSL Hypergeometric 2F1 for equal length vectors
#'
#' @param vA Vector of values for parameter a
#' @param vB Vector of values for parameter b
#' @param vC Vector of values for parameter c
#' @param vZ Vector of values for parameter z
#'
#' @description Calculate the hypergeometric 2f1 using the GSL library (gsl_sf_hyperg_2F1_e)
#' @return List with vector of values and vector of gsl status codes
#' @keywords internal
vec_gsl_hyp2f1_e <- function(vA, vB, vC, vZ) {
    .Call(`_CLVTools_vec_gsl_hyp2f1_e`, vA, vB, vC, vZ)
}

#' @title Gamma-Gamma: Log-Likelihood Function
#'
#' @description
#' Calculates the Log-Likelihood value for the Gamma-Gamma model.
#'
#' @param vLogparams a vector containing the log of the parameters p, q, gamma
#' @param vX frequency vector of length n counting the numbers of purchases
#' @param vM_x the observed average spending for every customer during the calibration time.
#' @template template_param_rcppvn
#'
#' @details
#' \code{vLogparams} is a vector with the parameters for the Gamma-Gamma model.
#' It has three parameters (p, q, gamma). The scale parameter for each transaction
#' is distributed across customers according to a gamma distribution with
#' parameters q (shape) and gamma (scale).
#'
#'@return
#' Returns the Log-Likelihood value for the Gamma-Gamma model.
#'
#' @template template_references_gg
#'
#'
gg_LL <- function(vLogparams, vX, vM_x, vN) {
    .Call(`_CLVTools_gg_LL`, vLogparams, vX, vM_x, vN)
}

#' @name ggomnbd_CET
#'
#' @templateVar name_model_full GGompertz/NBD
#' @templateVar name_model_short ggomnbd
#' @template template_titledescriptionreturn_CET
#'
#' @template template_params_ggomnbd
#' @template template_params_rcppperiods
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_ggomnbd
#'
NULL

#' @name ggomnbd_expectation
#' @title GGompertz/NBD: Unconditional Expectation
#'
#' @template template_expectation_description
#'
#' @template template_params_ggomnbd
#' @template template_expectation_params
#' @param vAlpha_i Vector of individual parameters alpha
#' @param vBeta_i Vector of individual parameters beta
#'
#' @template template_references_ggomnbd
#'
#' @template template_expectation_return
#'
NULL

#' @name ggomnbd_LL
#'
#' @templateVar name_model_full GGompertz/NBD
#' @templateVar name_model_short ggomnbd
#' @templateVar model_params_ordered r, alpha_0, b, s, beta_0
#' @template template_titleparamsdescriptionreturndetails_LL
#'
#' @template template_params_rcppxtxtcal
#' @template template_param_rcppvn
#' @template template_params_rcppcovmatrix
#'
#' @templateVar name_params_cov_life vParams
#' @templateVar name_params_cov_trans vParams
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_ggomnbd
#'
NULL

#' @name ggomnbd_PAlive
#'
#' @templateVar name_model_full GGompertz/NBD
#' @templateVar name_model_short ggomnbd
#' @template template_titledescriptionreturn_palive
#'
#' @template template_params_ggomnbd
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_ggomnbd
#'
NULL

#' @name ggomnbd_PMF
#' @templateVar name_model_full GGompertz/NBD
#' @template template_pmf_titledescreturnpmfparams
#'
#' @template template_params_ggomnbd
#' @template template_params_rcppvcovparams
#' @template template_params_rcppcovmatrix
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_ggomnbd
#'
NULL

#' @rdname ggomnbd_CET
ggomnbd_nocov_CET <- function(r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_ggomnbd_nocov_CET`, r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal)
}

#' @rdname ggomnbd_CET
ggomnbd_staticcov_CET <- function(r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans) {
    .Call(`_CLVTools_ggomnbd_staticcov_CET`, r, alpha_0, b, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans)
}

#' @rdname ggomnbd_expectation
ggomnbd_nocov_expectation <- function(r, alpha_0, b, s, beta_0, vT_i) {
    .Call(`_CLVTools_ggomnbd_nocov_expectation`, r, alpha_0, b, s, beta_0, vT_i)
}

#' @rdname ggomnbd_expectation
ggomnbd_staticcov_expectation <- function(r, b, s, vAlpha_i, vBeta_i, vT_i) {
    .Call(`_CLVTools_ggomnbd_staticcov_expectation`, r, b, s, vAlpha_i, vBeta_i, vT_i)
}

#' @rdname ggomnbd_LL
ggomnbd_nocov_LL_ind <- function(vLogparams, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_ggomnbd_nocov_LL_ind`, vLogparams, vX, vT_x, vT_cal)
}

#' @rdname ggomnbd_LL
ggomnbd_nocov_LL_sum <- function(vLogparams, vX, vT_x, vT_cal, vN) {
    .Call(`_CLVTools_ggomnbd_nocov_LL_sum`, vLogparams, vX, vT_x, vT_cal, vN)
}

#' @rdname ggomnbd_LL
ggomnbd_staticcov_LL_ind <- function(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans) {
    .Call(`_CLVTools_ggomnbd_staticcov_LL_ind`, vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans)
}

#' @rdname ggomnbd_LL
ggomnbd_staticcov_LL_sum <- function(vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans) {
    .Call(`_CLVTools_ggomnbd_staticcov_LL_sum`, vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans)
}

ggomnbd_staticcov_alpha_i <- function(alpha_0, vCovParams_trans, mCov_trans) {
    .Call(`_CLVTools_ggomnbd_staticcov_alpha_i`, alpha_0, vCovParams_trans, mCov_trans)
}

ggomnbd_staticcov_beta_i <- function(beta_0, vCovParams_life, mCov_life) {
    .Call(`_CLVTools_ggomnbd_staticcov_beta_i`, beta_0, vCovParams_life, mCov_life)
}

#' @rdname ggomnbd_PAlive
ggomnbd_staticcov_PAlive <- function(r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans) {
    .Call(`_CLVTools_ggomnbd_staticcov_PAlive`, r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans)
}

#' @rdname ggomnbd_PAlive
ggomnbd_nocov_PAlive <- function(r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_ggomnbd_nocov_PAlive`, r, alpha_0, b, s, beta_0, vX, vT_x, vT_cal)
}

#' @rdname ggomnbd_PMF
ggomnbd_nocov_PMF <- function(r, alpha_0, b, s, beta_0, x, vT_i) {
    .Call(`_CLVTools_ggomnbd_nocov_PMF`, r, alpha_0, b, s, beta_0, x, vT_i)
}

#' @rdname ggomnbd_PMF
ggomnbd_staticcov_PMF <- function(r, alpha_0, b, s, beta_0, x, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans, vT_i) {
    .Call(`_CLVTools_ggomnbd_staticcov_PMF`, r, alpha_0, b, s, beta_0, x, vCovParams_trans, vCovParams_life, mCov_life, mCov_trans, vT_i)
}

#' @name pnbd_CET
#'
#' @templateVar name_model_full Pareto/NBD
#' @templateVar name_model_short pnbd
#' @template template_titledescriptionreturn_CET
#'
#' @template template_params_pnbd
#' @template template_params_rcppperiods
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_pnbd
#'
NULL

#' @name pnbd_DERT
#'
#' @title Pareto/NBD: Discounted Expected Residual Transactions
#'
#' @description
#' Calculates the discounted expected residual transactions.
#'
#' \describe{
#' \item{\code{pnbd_nocov_DERT}}{ Discounted expected residual transactions for the Pareto/NBD model without covariates}
#' \item{\code{pnbd_staticcov_DERT}}{ Discounted expected residual transactions for the Pareto/NBD model with static covariates}
#' }
#'
#' @template template_params_pnbd
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#' @param continuous_discount_factor continuous discount factor to use
#'
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @return
#' Returns a vector with the DERT for each customer.
#'
#' @template template_references_pnbd
#'
#'
NULL

#' @name pnbd_expectation
#' @title Pareto/NBD: Unconditional Expectation
#'
#' @template template_expectation_description
#'
#' @template template_params_pnbd
#' @template template_expectation_params
#' @param vAlpha_i Vector of individual parameters alpha
#' @param vBeta_i Vector of individual parameters beta
#'
#'
#' @template template_references_pnbd
#'
#' @template template_expectation_return
#'
NULL

#' @name pnbd_LL
#'
#' @templateVar name_model_full Pareto/NBD
#' @templateVar name_model_short pnbd
#' @templateVar model_params_ordered r, alpha_0, s, beta_0
#' @template template_titleparamsdescriptionreturndetails_LL
#'
#' @template template_params_rcppxtxtcal
#' @template template_param_rcppvn
#' @template template_params_rcppcovmatrix
#'
#' @templateVar name_params_cov_life vParams
#' @templateVar name_params_cov_trans vParams
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_pnbd
#'
NULL

#' @name pnbd_PAlive
#'
#' @templateVar name_model_full Pareto/NBD
#' @templateVar name_model_short pnbd
#' @template template_titledescriptionreturn_palive
#'
#' @template template_params_pnbd
#' @template template_params_rcppxtxtcal
#' @template template_params_rcppcovmatrix
#' @template template_params_rcppvcovparams
#'
#' @templateVar name_params_cov_life vCovParams_life
#' @templateVar name_params_cov_trans vCovParams_trans
#' @template template_details_rcppcovmatrix
#'
#' @template template_references_pnbd
#'
NULL

#' @name pnbd_pmf
#' @templateVar name_model_full Pareto/NBD
#' @template template_pmf_titledescreturnpmfparams
#' @template template_params_pnbd
#' @param vAlpha_i Vector of individual parameters alpha.
#' @param vBeta_i Vector of individual parameters beta.
#' @template template_references_pnbd
#'
NULL

#' @rdname pnbd_CET
pnbd_nocov_CET <- function(r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_pnbd_nocov_CET`, r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal)
}

#' @rdname pnbd_CET
pnbd_staticcov_CET <- function(r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life) {
    .Call(`_CLVTools_pnbd_staticcov_CET`, r, alpha_0, s, beta_0, dPeriods, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life)
}

#' @rdname pnbd_DERT
pnbd_nocov_DERT <- function(r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_pnbd_nocov_DERT`, r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal)
}

#' @rdname pnbd_DERT
pnbd_staticcov_DERT <- function(r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal, mCov_life, mCov_trans, vCovParams_life, vCovParams_trans) {
    .Call(`_CLVTools_pnbd_staticcov_DERT`, r, alpha_0, s, beta_0, continuous_discount_factor, vX, vT_x, vT_cal, mCov_life, mCov_trans, vCovParams_life, vCovParams_trans)
}

#' @rdname pnbd_expectation
pnbd_nocov_expectation <- function(r, s, alpha_0, beta_0, vT_i) {
    .Call(`_CLVTools_pnbd_nocov_expectation`, r, s, alpha_0, beta_0, vT_i)
}

#' @rdname pnbd_expectation
pnbd_staticcov_expectation <- function(r, s, vAlpha_i, vBeta_i, vT_i) {
    .Call(`_CLVTools_pnbd_staticcov_expectation`, r, s, vAlpha_i, vBeta_i, vT_i)
}

#' @rdname pnbd_LL
pnbd_nocov_LL_ind <- function(vLogparams, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_pnbd_nocov_LL_ind`, vLogparams, vX, vT_x, vT_cal)
}

#' @rdname pnbd_LL
pnbd_nocov_LL_sum <- function(vLogparams, vX, vT_x, vT_cal, vN) {
    .Call(`_CLVTools_pnbd_nocov_LL_sum`, vLogparams, vX, vT_x, vT_cal, vN)
}

#' @rdname pnbd_LL
pnbd_staticcov_LL_ind <- function(vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans) {
    .Call(`_CLVTools_pnbd_staticcov_LL_ind`, vParams, vX, vT_x, vT_cal, mCov_life, mCov_trans)
}

#' @rdname pnbd_LL
pnbd_staticcov_LL_sum <- function(vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans) {
    .Call(`_CLVTools_pnbd_staticcov_LL_sum`, vParams, vX, vT_x, vT_cal, vN, mCov_life, mCov_trans)
}

pnbd_staticcov_alpha_i <- function(alpha_0, vCovParams_trans, mCov_trans) {
    .Call(`_CLVTools_pnbd_staticcov_alpha_i`, alpha_0, vCovParams_trans, mCov_trans)
}

pnbd_staticcov_beta_i <- function(beta_0, vCovParams_life, mCov_life) {
    .Call(`_CLVTools_pnbd_staticcov_beta_i`, beta_0, vCovParams_life, mCov_life)
}

#' @rdname pnbd_PAlive
pnbd_nocov_PAlive <- function(r, alpha_0, s, beta_0, vX, vT_x, vT_cal) {
    .Call(`_CLVTools_pnbd_nocov_PAlive`, r, alpha_0, s, beta_0, vX, vT_x, vT_cal)
}

#' @rdname pnbd_PAlive
pnbd_staticcov_PAlive <- function(r, alpha_0, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life) {
    .Call(`_CLVTools_pnbd_staticcov_PAlive`, r, alpha_0, s, beta_0, vX, vT_x, vT_cal, vCovParams_trans, vCovParams_life, mCov_trans, mCov_life)
}

#' @rdname pnbd_pmf
pnbd_nocov_PMF <- function(r, alpha_0, s, beta_0, x, vT_i) {
    .Call(`_CLVTools_pnbd_nocov_PMF`, r, alpha_0, s, beta_0, x, vT_i)
}

#' @rdname pnbd_pmf
pnbd_staticcov_PMF <- function(r, s, x, vAlpha_i, vBeta_i, vT_i) {
    .Call(`_CLVTools_pnbd_staticcov_PMF`, r, s, x, vAlpha_i, vBeta_i, vT_i)
}

pnbd_dyncov_LL_negsum <- function(params, X, t_x, T_cal, d_omega, vN, walkinfo_aux_life, walkinfo_real_life, walkinfo_aux_trans, walkinfo_real_trans, walkinfo_trans_real_from, walkinfo_trans_real_to, covdata_aux_life, covdata_real_life, covdata_aux_trans, covdata_real_trans) {
    .Call(`_CLVTools_pnbd_dyncov_LL_negsum`, params, X, t_x, T_cal, d_omega, vN, walkinfo_aux_life, walkinfo_real_life, walkinfo_aux_trans, walkinfo_real_trans, walkinfo_trans_real_from, walkinfo_trans_real_to, covdata_aux_life, covdata_real_life, covdata_aux_trans, covdata_real_trans)
}

pnbd_dyncov_LL_ind <- function(params, X, t_x, T_cal, d_omega, walkinfo_aux_life, walkinfo_real_life, walkinfo_aux_trans, walkinfo_real_trans, walkinfo_trans_real_from, walkinfo_trans_real_to, covdata_aux_life, covdata_real_life, covdata_aux_trans, covdata_real_trans, return_intermediate_results = FALSE) {
    .Call(`_CLVTools_pnbd_dyncov_LL_ind`, params, X, t_x, T_cal, d_omega, walkinfo_aux_life, walkinfo_real_life, walkinfo_aux_trans, walkinfo_real_trans, walkinfo_trans_real_from, walkinfo_trans_real_to, covdata_aux_life, covdata_real_life, covdata_aux_trans, covdata_real_trans, return_intermediate_results)
}

#' @name pnbd_dyncov_pmf_hyp2f1_C
#' @title GSL Hypergeometric 2F1 wrapper for dynamic covariates
#' @description Calculates the hypergeometric function 2F1(a,b,c,z) with error checking
#' 
#' @param a First parameter of hypergeometric function
#' @param b Second parameter of hypergeometric function
#' @param c Third parameter of hypergeometric function
#' @param z Argument of hypergeometric function
#'
#' @details 
#' This function wraps the GSL implementation of the hypergeometric function with
#' additional error handling for parameter validation, convergence issues, and
#' special cases. It plays a critical role in calculating the probability
#' mass function for the Pareto/NBD model with dynamic covariates.
#'
#' @return Value of the hypergeometric function or NaN if calculation fails
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_A_i_C
#' @title Get transaction covariate effect for a specific time period
#' @description Retrieves the transaction covariate effect for a specific period index
#' 
#' @param i_1based One-based index of the period to retrieve
#' @param dt_data_period_customer_trans Dynamic covariates object containing transaction effects
#'
#' @return Covariate effect value for the specified period
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_C_i_C
#' @title Get lifetime covariate effect for a specific time period
#' @description Retrieves the lifetime/dropout covariate effect for a specific period index
#' 
#' @param i_1based One-based index of the period to retrieve
#' @param dt_data_period_customer_life Dynamic covariates object containing lifetime effects
#'
#' @return Covariate effect value for the specified period
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_Bbar_i_C
#' @title Calculate adjusted cumulative transaction covariate effect
#' @description Computes Bbar_i, the adjusted cumulative transaction covariate effect
#'
#' @param i_1based One-based index of the period to calculate up to
#' @param dt_data_period_customer_trans Dynamic covariates object containing transaction effects
#' @param d1 Fraction of time between first transaction and next covariate date
#' @param ui Time between customer's first transaction and start of estimation period
#'
#' @return Adjusted cumulative transaction covariate effect
#'
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_Dbar_i_C
#' @title Calculate adjusted cumulative dropout covariate effect
#' @description Computes Dbar_i, the adjusted cumulative dropout covariate effect
#' 
#' @param i_1based_period One-based index of the period to calculate
#' @param dt_data_period_customer_life Dynamic covariates object for lifetime in period
#' @param dt_data_since_alive_customer_life Dynamic covariates object for lifetime since alive
#' @param d_omega Fraction of time from period start until next time unit
#' @param k0u_Dbar Number of time units between customer's first transaction and start of period
#'
#' @return Adjusted cumulative dropout covariate effect
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_bu_i_C
#' @title Calculate time boundary for period i
#' @description Computes the time boundary bu_i for the specified period
#' 
#' @param ui Time between customer's first transaction and start of estimation period
#' @param i_1based One-based index of the period
#' @param d1 Fraction of time between first transaction and next covariate date
#'
#' @return Time boundary value
#' 
#' @keywords internal
NULL

#' @name factorial_C
#' @title Compute factorial using gamma function
#' @description Calculates factorial using the gamma function for numerical stability
#' 
#' @param n Integer value for which to calculate factorial
#'
#' @return The factorial of n
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_S1_per_customer_C
#' @title Calculate S1 component of PMF
#' @description Computes the S1 component of the Pareto/NBD PMF with dynamic covariates
#' 
#' @param dt_data_period_customer_trans Dynamic covariates for transaction process
#' @param dt_data_period_customer_life Dynamic covariates for lifetime process
#' @param dt_data_since_alive_customer_life Dynamic covariates for lifetime since first transaction
#' @param x_double Number of transactions
#' @param alpha_r Scale parameter for transaction rate distribution
#' @param beta_s Scale parameter for dropout rate distribution
#' @param r Shape parameter for transaction rate distribution
#' @param s Shape parameter for dropout rate distribution
#' @param t_r Time span for prediction
#' @param ui Time between customer's first transaction and start of estimation period
#' @param d1 Fraction of time between first transaction and next covariate date
#' @param d_omega Fraction of time from period start until next time unit
#' @param k0u_S1 Number of time units between customer's first transaction and period start
#'
#' @details 
#' S1 represents the probability that a customer makes exactly x transactions in the 
#' prediction period conditional on being alive throughout the entire period.
#'
#' @return S1 component value
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_S2_1j_per_customer_C
#' @title Calculate S2_1j component of PMF
#' @description Computes the S2_1j component of the Pareto/NBD PMF with dynamic covariates
#' 
#' @param dt_data_period_customer_trans Dynamic covariates for transaction process
#' @param dt_data_period_customer_life Dynamic covariates for lifetime process
#' @param dt_data_since_alive_customer_life Dynamic covariates for lifetime since first transaction
#' @param j_S2_1j Number of transactions at time of churn
#' @param x_double Total number of transactions
#' @param alpha_r Scale parameter for transaction rate distribution
#' @param beta_s Scale parameter for dropout rate distribution
#' @param r_param Shape parameter for transaction rate distribution
#' @param s_param Shape parameter for dropout rate distribution
#' @param ui Time between customer's first transaction and start of estimation period
#' @param d1 Fraction of time between first transaction and next covariate date
#' @param d_omega Fraction of time from period start until next time unit
#' @param k0u_S2_1j Number of time units between customer's first transaction and period start
#'
#' @details 
#' S2_1j represents the probability that a customer churns during the first period
#' with exactly j transactions at the time of churn, and makes a total of x transactions.
#'
#' @return S2_1j component value
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_S2_ij_per_customer_C
#' @title Calculate S2_ij component of PMF
#' @description Computes the S2_ij component of the Pareto/NBD PMF with dynamic covariates
#' 
#' @param dt_data_period_customer_trans Dynamic covariates for transaction process
#' @param dt_data_period_customer_life Dynamic covariates for lifetime process
#' @param dt_data_since_alive_customer_life Dynamic covariates for lifetime since first transaction
#' @param i_S2_1based Period index in which customer churns
#' @param j_S2 Number of transactions at time of churn
#' @param x_double Total number of transactions
#' @param alpha_r Scale parameter for transaction rate distribution
#' @param beta_s Scale parameter for dropout rate distribution
#' @param r_param Shape parameter for transaction rate distribution
#' @param s_param Shape parameter for dropout rate distribution
#' @param ui Time between customer's first transaction and start of estimation period
#' @param d1 Fraction of time between first transaction and next covariate date
#' @param d_omega Fraction of time from period start until next time unit
#' @param k0u_S2_ij Number of time units between customer's first transaction and period start
#'
#' @details 
#' S2_ij represents the probability that a customer churns during period i
#' with exactly j transactions at the time of churn, and makes a total of x transactions.
#'
#' @return S2_ij component value
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_S2_kutuj_per_customer_C
#' @title Calculate S2_kutuj component of PMF
#' @description Computes the S2_kutuj component of the Pareto/NBD PMF with dynamic covariates
#' 
#' @param dt_data_period_customer_trans Dynamic covariates for transaction process
#' @param dt_data_period_customer_life Dynamic covariates for lifetime process
#' @param dt_data_since_alive_customer_life Dynamic covariates for lifetime since first transaction
#' @param j_S2_kutu Number of transactions at time of churn
#' @param x_double Total number of transactions
#' @param r_param Shape parameter for transaction rate distribution
#' @param alpha_r Scale parameter for transaction rate distribution
#' @param s_param Shape parameter for dropout rate distribution
#' @param beta_s Scale parameter for dropout rate distribution
#' @param t_r Time span for prediction
#' @param ui Time between customer's first transaction and start of estimation period
#' @param d1 Fraction of time between first transaction and next covariate date
#' @param d_omega Fraction of time from period start until next time unit
#' @param k0u_S2_kutu Number of time units between customer's first transaction and period start
#'
#' @details 
#' S2_kutuj represents the probability that a customer churns during the last period
#' with exactly j transactions at the time of churn, and makes a total of x transactions.
#'
#' @return S2_kutuj component value
#' 
#' @keywords internal
NULL

#' @name pnbd_dyncov_pmf_per_customer
#' @title PNBD Dynamic Covariates PMF Per Customer
#' @description Calculate the probability mass function (PMF) for Pareto/NBD model with dynamic covariates for a single customer
#' 
#' @param cov_period_life_exp Pre-computed exp(γ*X) for lifetime process in the period (u, tu]; sorted by date
#' @param cov_period_trans_exp Pre-computed exp(β*X) for transaction process in the period (u, tu]; sorted by date
#' @param cov_sincealive_life_exp Pre-computed exp(γ*X) for lifetime process from customer's first transaction; sorted by date
#' @param r_param Shape parameter r for the transaction rate gamma distribution
#' @param alpha_r_param Scale parameter α for the transaction rate gamma distribution
#' @param s_param Shape parameter s for the dropout rate gamma distribution  
#' @param beta_s_param Scale parameter β for the dropout rate gamma distribution
#' @param x_double Number of transactions to calculate PMF for
#' @param t_r_param Time from start of period (u) to end of period (tu)
#' @param d1_param Fraction of time between first transaction and next covariate date
#' @param d_omega_param Fraction of time from u to next time unit
#' @param k0u_param Number of time units between customer's first transaction and beginning of period
#' @param ui_param Time between customer's first transaction and start of estimation period u
#'
#' @details
#' The dynamic covariate Pareto/NBD model extends the standard model by allowing the transaction and 
#' dropout rates to vary over time according to time-varying covariates:
#' 
#' λ(t) = λ * exp(β*X(t)) for transaction rate
#' μ(t) = μ * exp(γ*X(t)) for dropout rate
#' 
#' Where:
#' - λ and μ are the base rates (linked to parameters r, α, s, β)
#' - β and γ are coefficient vectors for the covariates
#' - X(t) are time-varying covariates at time t
#' 
#' Formula structure follows PMF = S1 + S2, where:
#' - S1 represents probability for a customer who has not churned in period (u, t+u] and makes exactly x transactions
#' - S2 represents probability for a customer who has churned during period (u, t+u] and makes exactly x transactions
#'   (this is further decomposed into sums over all possible churn times and transaction patterns)
#'
#' @return The probability mass function value for the specified number of transactions
#'
#' @keywords internal
pnbd_dyncov_pmf_per_customer <- function(cov_period_life_exp, cov_period_trans_exp, cov_sincealive_life_exp, cov_sincealive_trans_exp, r_param, alpha_r_param, s_param, beta_s_param, x_double, t_r_param, d1_param, d_omega_param, k0u_param, ui_param) {
    .Call(`_CLVTools_pnbd_dyncov_pmf_per_customer`, cov_period_life_exp, cov_period_trans_exp, cov_sincealive_life_exp, cov_sincealive_trans_exp, r_param, alpha_r_param, s_param, beta_s_param, x_double, t_r_param, d1_param, d_omega_param, k0u_param, ui_param)
}

