name: coverage
on: pull_request # default to types [opened, synchronize, reopened]
jobs:
  coverage-ubuntu-20-04-R-release:
    runs-on: ubuntu-20.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # to install binaries on ubuntu
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: release

      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages(c('remotes'))"
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements(os="ubuntu", os_release="20.04"))')

      - name: Install package dependencies
        run: |
          remotes::install_deps(dependencies = TRUE) # installs binaries
          # testthat and covr are part of package's Suggests and installed as package dependency.
        shell: Rscript {0}

      - name: Test coverage
        # run: covr::codecov() # uploads to codecov.io
        run: |
          # If on a release branch (name starts with 'release'),
          #   run all tests, including lengthy ones marked with skip_on_ci/skip_on_covr()
          if(grepl(pattern = "^release", x = Sys.getenv("GITHUB_HEAD_REF"))){
            Sys.setenv(R_COVR="")
            print("On release branch: Run all coverage tests (setting R_COVR='')")
          }else{
            print("Not on release branch: Dont run all tests (skip_on_covr())")
          }

          covr::package_coverage(type = "tests", quiet = FALSE)
        shell: Rscript {0}
