name: coverage
on: pull_request # default to types [opened, synchronize, reopened]
jobs:
  coverage-ubuntu-16-04-R-release:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      # to install binaries on ubuntu
      RSPM: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
      - name: Install system dependencies
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Install package dependencies
        run: |
          remotes::install_deps(dependencies = TRUE) # installs binaries
          # testthat and covr are part of package's Suggests and installed as package dependency.
        shell: Rscript {0}

      - name: Test coverage
        # run: covr::codecov() # uploads to codecov.io
        run: covr::package_coverage(type = "tests", quiet = FALSE)
        shell: Rscript {0}
